package com.training.pom;

import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.support.FindBy;
import org.openqa.selenium.support.PageFactory;

public class ShoppingCartOrdersPOM_Retail {
	private WebDriver driver; 
	
	public ShoppingCartOrdersPOM_Retail(WebDriver driver) {
		this.driver = driver; 
		PageFactory.initElements(driver, this);
	}
	
	// locating the WebElement view image by xpath. 
	@FindBy(xpath="//table/tbody/tr[5]/td[8]/a")
	private WebElement view; 
	
	// locating the WebElement invoice button by id 
	@FindBy(id="button-invoice")
	private WebElement invoicebutton; 
	
// locating the WebElement invoice number generated by x path.
	@FindBy(xpath="//td[contains(text(),'INV')]")
	private WebElement invoicenumber; 
	
	
	// method to get the text once invoice number is generated.
	public String invoicenumber() {
		
     return this.invoicenumber.getText();

	}
	
	// method to click on view image/icon on customer order details screen.	
	public void ClickonView() {
		this.view.click();
		
	}
	
	// method to click on invoice button on customer order details screen.
	public void Clickoninvoicebutton() {
		this.invoicebutton.click();
		
	}	
	
	
	
}
